### ISSUE TITLE
Adding support for `core::range::Range` API.

### ISSUE THREAD

**Issue by ghost** [conradludgate/dbg-pls#10]
Hello, im using dbg-pls for showing my ast in a pretty and coincise way. im using the new Range API since it implements copy and generally is more handy, i noticed there isn't support as when i try to derive `DebugPls` for this struct 
```rust
#[cfg_attr(feature = "dbg-pls", derive(dbg_pls::DebugPls))]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct Spanned<T>(pub Range<usize>, pub T);
```
i get the following error:
![image](https://github.com/user-attachments/assets/3b7a9127-d895-47a1-b891-560db6498259)

**Comment by conradludgate** [comment]
I can support it when it becomes stable. Supporting nightly types would be too much effort.
